update basic-chi
G3-KKA/templates pull request #10
Opened 2024-06-21 21:14 UTC by dmitryzhvinklis

2024-06-21 21:15 UTC, dmitryzhvinklis reviewed
поубирал ошибки ,крупного изменения нет ,поубирал комменты ,сократил некоторые строчки

2024-06-22 09:43 UTC, G3-KKA commented on basicchi/server.go
> +// запуск
Я бы хотел, чтобы комменты в этих шаблонах были на английском, это как-то больше соответствует общему стилю в Golang

2024-06-22 09:47 UTC, G3-KKA requested changes
Требуется парочка небольших правок, в основном все супер .

2024-06-22 09:47 UTC, G3-KKA commented on basicchi/server.go
> -	/*  ===  cannot use after __ANY__ .Handle === */
Этот коммент не стоило убирать, скорее нужно бы переписать, он о том, что .Use( . . . ) необходимо регистрировать исключительно до вызовов .Handle() или .HandleFunc()

2024-06-22 09:47 UTC, G3-KKA commented on basicchi/server.go
> +// Middleware для логирования
Тоже самое по поводу русского в комментах

2024-06-22 09:47 UTC, G3-KKA commented on basicchi/server.go
> +		/* логирование */
Тоже самое по поводу русского в комментах

2024-07-27 10:08 UTC, closed without merging